# Generated by Django 3.1.7 on 2022-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_table_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=122)),
                ('service', models.CharField(max_length=122)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact_table',
        ),
    ]
