# Generated by Django 3.1.7 on 2022-05-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_contact_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default='00-00-00'),
        ),
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(default='-1'),
        ),
    ]
