# Generated by Django 3.1.7 on 2022-05-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220507_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='service',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text',
        ),
    ]
