# Generated by Django 3.1.7 on 2022-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220507_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(default='-1'),
        ),
    ]
