# Generated by Django 3.1.7 on 2022-05-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
